// Generated by js2wasm — shared runtime imports helper
// Shared host glue comes from the js2wasm runtime so it only needs to ship once.
// Usage: import { createImports, instantiateBytes, instantiateFromUrl } from "./module.imports.js";

import { buildImports, instantiateWasm, instantiateWasmStreaming } from "js2wasm";

const manifest = [];
const stringPool = [
  "TypeError: Cannot access property on null or undefined",
  "TypeError: Cannot access property on null or undefined at 41:37",
  "TypeError: Cannot access property on null or undefined at 42:7",
  "TypeError: Cannot access property on null or undefined at 43:7",
  "TypeError: Cannot access property on null or undefined at 51:37",
  "TypeError: Cannot access property on null or undefined at 52:5",
  "TypeError: Cannot access property on null or undefined at 62:51",
  "TypeError: Cannot access property on null or undefined at 73:7",
  "TypeError: Cannot access property on null or undefined at 83:5",
  "TypeError: Cannot access property on null or undefined at 84:5",
  "TypeError: Cannot access property on null or undefined at 85:59",
  "TypeError: Cannot access property on null or undefined at 99:23",
  "TypeError: Cannot access property on null or undefined at 100:65",
  "TypeError: Cannot access property on null or undefined at 107:7",
  "TypeError: Cannot access property on null or undefined at 108:60",
  "TypeError: Cannot access property on null or undefined at 114:5",
  "TypeError: Array method called on null or undefined",
  "TypeError: Cannot access property on null or undefined at 136:75",
  "TypeError: Cannot access property on null or undefined at 153:7",
  "TypeError: Cannot access property on null or undefined at 154:7",
  "TypeError: Cannot access property on null or undefined at 160:9",
  "TypeError: Cannot access property on null or undefined at 161:9",
  "TypeError: Cannot access property on null or undefined at 167:5",
  "TypeError: Cannot access property on null or undefined at 168:35",
  "TypeError: Cannot access property on null or undefined at 168:50",
  "TypeError: Cannot access property on null or undefined at 184:32",
  "TypeError: Cannot access property on null or undefined at 187:5",
  "TypeError: Cannot access property on null or undefined at 188:5",
  "TypeError: Cannot access property on null or undefined at 206:5",
  "TypeError: Cannot access property on null or undefined at 208:60",
  "TypeError",
  "Cannot convert null or undefined to a BigInt",
  "Cannot convert value to a BigInt",
  "RangeError",
  "The number cannot be converted to a BigInt because it is not an integer",
  "SyntaxError",
  "Cannot convert string to a BigInt in standalone mode",
  "[[PrimitiveValue]]",
  "Cannot convert object to primitive value",
  "toString",
  "[object Object]",
  "valueOf",
  "string",
  "TypeError: Cannot define property, object is not extensible",
  "TypeError: Cannot redefine property: configurable attribute of a non-configurable property",
  "TypeError: Cannot redefine property: enumerable attribute of a non-configurable property",
  "TypeError: Cannot redefine property: cannot convert a non-configurable accessor to a data property",
  "TypeError: Cannot redefine property: writable attribute of a non-configurable, non-writable property",
  "TypeError: Cannot assign to read only property of a non-configurable property",
  "Object.defineProperties unsupported descriptor shape in standalone mode (#1906)",
  "TypeError: Object.defineProperties get/set must be callable (#1906)",
  "TypeError: Invalid property descriptor in Object.defineProperties (#1906)",
  "TypeError: Property description must be an object",
  "TypeError: Getter/setter must be a function",
  "TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute",
  "Cannot perform operation on a proxy that has been revoked",
  "Proxy ownKeys trap result must be an object",
  "Cannot create proxy with a non-object as target or handler",
  "TypeError: Cannot access property on null or undefined at 252:18",
  "TypeError: Cannot access property on null or undefined at 260:22",
  "TypeError: Cannot access property on null or undefined at 280:18",
  "TypeError: Cannot access property on null or undefined at 288:12",
  "TypeError: Cannot access property on null or undefined at 301:30",
  "TypeError: Cannot access property on null or undefined at 316:20",
  "TypeError: Cannot access property on null or undefined at 322:28"
];

export function createImports(deps, options) {
  return buildImports(manifest, deps, stringPool, options);
}

export async function instantiateBytes(wasmBytes, deps, options) {
  const imports = createImports(deps, options);
  const result = await instantiateWasm(wasmBytes, imports.env, imports.string_constants);
  if (imports.setExports) imports.setExports(result.instance.exports);
  return { ...result, imports };
}

export async function instantiateFromResponse(response, deps, options) {
  const imports = createImports(deps, options);
  const result = await instantiateWasmStreaming(response, imports.env, imports.string_constants);
  if (imports.setExports) imports.setExports(result.instance.exports);
  return { ...result, imports };
}

export async function instantiateFromUrl(url, deps, options) {
  return instantiateFromResponse(fetch(url), deps, options);
}
