// Generated by js2wasm — shared runtime imports helper
// Shared host glue comes from the js2wasm runtime so it only needs to ship once.
// Usage: import { createImports, instantiateBytes, instantiateFromUrl } from "./module.imports.js";

import { buildImports, instantiateWasm, instantiateWasmStreaming } from "js2wasm";

const manifest = [];
const stringPool = [
  "TypeError",
  "Cannot convert null or undefined to a BigInt",
  "Cannot convert value to a BigInt",
  "RangeError",
  "The number cannot be converted to a BigInt because it is not an integer",
  "SyntaxError",
  "Cannot convert string to a BigInt in standalone mode",
  "[[PrimitiveValue]]",
  "Cannot convert object to primitive value",
  "toString",
  "[object Object]",
  "valueOf",
  "string",
  "TypeError: Cannot define property, object is not extensible",
  "TypeError: Cannot redefine property: configurable attribute of a non-configurable property",
  "TypeError: Cannot redefine property: enumerable attribute of a non-configurable property",
  "TypeError: Cannot redefine property: cannot convert a non-configurable accessor to a data property",
  "TypeError: Cannot redefine property: writable attribute of a non-configurable, non-writable property",
  "TypeError: Cannot assign to read only property of a non-configurable property",
  "Object.defineProperties unsupported descriptor shape in standalone mode (#1906)",
  "TypeError: Object.defineProperties get/set must be callable (#1906)",
  "TypeError: Invalid property descriptor in Object.defineProperties (#1906)",
  "TypeError: Property description must be an object",
  "TypeError: Getter/setter must be a function",
  "TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute",
  "Cannot perform operation on a proxy that has been revoked",
  "Proxy ownKeys trap result must be an object",
  "Cannot create proxy with a non-object as target or handler"
];

export function createImports(deps, options) {
  return buildImports(manifest, deps, stringPool, options);
}

export async function instantiateBytes(wasmBytes, deps, options) {
  const imports = createImports(deps, options);
  const result = await instantiateWasm(wasmBytes, imports.env, imports.string_constants);
  if (imports.setExports) imports.setExports(result.instance.exports);
  return { ...result, imports };
}

export async function instantiateFromResponse(response, deps, options) {
  const imports = createImports(deps, options);
  const result = await instantiateWasmStreaming(response, imports.env, imports.string_constants);
  if (imports.setExports) imports.setExports(result.instance.exports);
  return { ...result, imports };
}

export async function instantiateFromUrl(url, deps, options) {
  return instantiateFromResponse(fetch(url), deps, options);
}
